//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleAspServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public decimal Id { get; set; }
        public string senderUserName { get; set; }
        public string senderPhoneNumber { get; set; }
        public string receiverUserName { get; set; }
        public string receiverPhoneNumber { get; set; }
        public string messageData { get; set; }
    }
}
